<a href="https://colab.research.google.com/github/prashantlal56/Hotel_booking_demand/blob/master/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
df = pd.read_excel('Folds5x2_pp.xlsx')
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
print(X), print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


(None, None)

### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu', ))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units = 1 ))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, epochs=100,  batch_size = 32)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 22757.8027
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 587.1633
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 563.6087
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 532.5492
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 498.8061
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 461.0270
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 421.7606
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 381.0196
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 338.3008
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 297.2922
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 256.3669
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

### Predicting the results of the Test set

In [23]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[429.72 431.23]
 [460.66 460.01]
 [464.11 461.14]
 ...
 [471.4  473.26]
 [438.23 438.  ]
 [457.42 463.28]]
